name: just-learn
region: nyc1
static_sites:
- name: just-learn-site
  github:
    repo: ever-just/just-learn
    branch: main
    deploy_on_push: true
  index_document: index.html
  error_document: index.html
  build_command: ""
  environment_slug: html
domains:
- domain: learn.everjust.app
  type: PRIMARY
